# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-28 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_auto_20171027_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiences',
            name='description',
        ),
        migrations.RemoveField(
            model_name='experiences',
            name='title',
        ),
        migrations.AddField(
            model_name='experiencelanguage',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companies',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='responsable',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='responsible_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
