# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-01 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_auto_20171028_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='educationsuser',
            name='type_educations',
            field=models.SmallIntegerField(choices=[(1, 'Basic'), (2, 'Diversified'), (3, 'Academic')], default=1),
        ),
    ]
