# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-15 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0006_portfoliouser'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliouser',
            name='description_en',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfoliouser',
            name='description_es',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
