# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-29 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0007_auto_20171215_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiences',
            name='currently',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='experiences',
            name='ending_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
