# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-02 00:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_about_me'),
    ]

    operations = [
        migrations.CreateModel(
            name='WpUsers',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('user_login', models.CharField(max_length=60)),
                ('user_pass', models.CharField(max_length=255)),
                ('user_nicename', models.CharField(max_length=50)),
                ('user_email', models.CharField(max_length=100)),
                ('user_url', models.CharField(max_length=100)),
                ('user_registered', models.DateTimeField()),
                ('user_activation_key', models.CharField(max_length=255)),
                ('user_status', models.IntegerField()),
                ('display_name', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'wp_users',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='userwp',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.WpUsers'),
        ),
    ]
