# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-08 19:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20171202_0013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wpusers',
            options={},
        ),
    ]
