# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-21 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20171208_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='curriculum',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
