# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-02 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_wpposts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='curriculum',
            new_name='curriculum_en',
        ),
        migrations.AddField(
            model_name='user',
            name='curriculum_es',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
